title: Loki's Reach Wiki
description: >
  Sector information and rules reference.
show_downloads: false
theme: jekyll-theme-minimal
permalink: pretty
baseurl: lokis-reach-wiki
defaults:
  -
    scope:
      path: ""
    values:
      layout: default
collections:
  planets:
    output: true
  rules:
    output: true
